// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADTW5nAk-HGCowUdD3PDgX-V742UMfRJo',
    appId: '1:382795080487:android:9b8c5e266f9bd3192f3f02',
    messagingSenderId: '382795080487',
    projectId: 'prepas-concours',
    storageBucket: 'prepas-concours.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhc_LH_Iejx4XoJUQEziE_iftgvDQE-1g',
    appId: '1:382795080487:ios:a74cd823e63bbd6f2f3f02',
    messagingSenderId: '382795080487',
    projectId: 'prepas-concours',
    storageBucket: 'prepas-concours.firebasestorage.app',
    androidClientId: '382795080487-580idukuef0a8rcfgl9b6pq872n0u09o.apps.googleusercontent.com',
    iosClientId: '382795080487-vuagh1vcqa5qk2spte24e82r8ov9afjk.apps.googleusercontent.com',
    iosBundleId: 'mutrix.app.concours',
  );

}